In [1]:
import numpy as np

def rediagonalization(current_matrix, coupling_matrix, type = 'sensing'):
    """Refine existing diagonalization matrix given a coupling matrix.

    Parameters
    ----------
        current_matrix: list of (list of int/float) or 2D numpy.ndarray
            The matrix to be refined.
        coupling_matrix: list of (list of int/float) or 2D numpy.ndarray
            The measured coupling. For sensing matrix, coupling_matrix[i][j] is
            the coupling ratio between the i-th component and j-th component
            of the displacement vector. Hence, the diagonal elements should be
            1. For actuation matrix, coupling matrix[i][j] is the ratio
            between the i-th component of displacement and j-th component in
            actuation. The diagonal elements should be comparable to the
            actuation efficiency of the particular DoF.
        type: string
            Specifying what kind of matrix we are diagonalizing. Either
            'sensing' or 'actuation'

    Returns
    -------
        numpy.ndarray
            The refined diagonalziation matrix.
    """
    current_matrix = np.array(current_matrix)
    coupling_matrix = np.array(coupling_matrix)
    diagonal_coupling = np.array(np.diag(np.diag(coupling_matrix)))
    if type == 'sensing':
        new_matrix = np.matmul(np.linalg.inv(coupling_matrix), current_matrix)
        return(new_matrix)
    elif type == 'actuation':
        new_matrix = np.matmul(current_matrix,
            np.matmul(np.linalg.inv(coupling_matrix), diagonal_coupling))
        return(new_matrix)
    else:
        print("Please specify type, either 'sensing' or 'actuation'.")
        return(None)
    
    

In [37]:
# sensing SRM OL2EUL

ol2eul=np.array([[-0.04892, -0.03073, -3.8702, 0], 
                 [2.56819, 0.05846, 1.26304, 0], 
                 [-0.02427, 3.28096, -0.01598, 0]])
coupling_matrix = np.array([[1, -0.0174, -0.00243],
                            [0, 1, 0.0029],
                            [0.0256, 0.00288, 1]])
C = np.array([[1,0,0],[(-69.3216+78.0996)/(120.5889-17.8238),1,0],[0,0,1]])
# np.matmul(C,coupling_matrix)
# (-69.3216+78.0996)/(120.5889-17.8238)
new_ol2eul = rediagonalization(current_matrix = ol2eul, coupling_matrix = coupling_matrix, type = 'sensing')
new_ol2eul = rediagonalization(current_matrix = new_ol2eul, coupling_matrix = C, type = 'sensing')
new_ol2eul

array([[-0.00430858, -0.02190462, -3.84803538,  0.        ],
       [ 2.56864954,  0.05081505,  1.5915031 ,  0.        ],
       [-0.03155635,  3.2813798 ,  0.07889281,  0.        ]])

In [38]:
# actuation SRM TM_EUL2OSEM

coupling_matrix = np.array([[0.0003736428499, 0.00017566015, -2.71734459e-6],
                            [-4.90803115e-5, 0.0184034, 6.434345769e-5],
                            [-5.651684397e-5, 0.0002424936, 0.00703429]])
coupling_matrix = coupling_matrix.T
eul2osem = np.array([[0.282, 1.128, -1.128],
                     [0.25, -1, -1],
                     [0.242, -0.968, 0.968],
                     [0.231, 0.924, 0.924]])
new_eul2osem = rediagonalization(current_matrix=eul2osem, coupling_matrix=coupling_matrix, type = 'actuation')
new_eul2osem

array([[ 0.27037208,  1.17360037, -1.10256781],
       [ 0.25877144, -0.95733506, -0.9482441 ],
       [ 0.25140669, -0.94429223,  1.01847005],
       [ 0.2223493 ,  0.94456124,  0.94518626]])

In [41]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])